import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanstackProvider from "@/components/TanStackProvider/TanStackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "NoteHub — Ваш ідеальний простір для нотаток",
    description:
      "Створюйте, редагуйте та діліться своїми ідеями легко та швидко.",
    url: "http://localhost:3000/",
    siteName: "NoteHub",
    images: [
      {
        url: "https://ac.goit.global/fullstack/react/notehub-og-meta.jpg", // Вказане зображення
        width: 1200,
        height: 630,
        alt: "NoteHub Обкладинка для соціальних мереж",
      },
    ],
    type: "website",
  },
};
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
  display: "swap",
});
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <TanstackProvider>
          <Header />
          <main>
            {children}
            {modal}
          </main>

          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
